- name: Update packages
  ansible.builtin.command: apt update -y
  become: yes

- name: Variables that are common across all OS types
  include_vars: "{{ lookup('first_found', dependencies) }}"
  vars:
    dependencies:
      files:
        - common.yml
      paths:
        - 'vars'

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', dependencies) }}"
  vars:
    dependencies:
      files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Install packages for Open5GS
  ansible.builtin.package:
    name: "{{ installation_packages }}"
    state: present
  become: yes

- name: Add open5gs latest repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:open5gs/latest
  become: yes

- name: Update packages
  ansible.builtin.command: apt update -y
  become: yes

- name: Install Open5GS
  ansible.builtin.package:
    name: "{{ open5gs }}"
    state: present
  become: yes

- name: Copy upf.yml file with owner and permissions
  ansible.builtin.copy:
    src: "{{ role_path }}/files/open5gs-dbctl"
    dest: '{{ ansible_user_dir }}/open5gs-dbctl'
    mode: 0755
  become: yes