bpftrace_compile_packages:
  - libbpfcc-dev
bpftrace_build_packages:
  - bison
  - cmake
  - flex
  - g++
  - git
  - libelf-dev
  - zlib1g-dev
  - libfl-dev
  - systemtap-sdt-dev
  - binutils-dev
  - libcereal-dev
  - llvm-7-dev
  - llvm-7-runtime
  - libclang-7-dev
  - clang-7
  - libgtest-dev
  - libgmock-dev
  - asciidoctor
  - linux-headers-{{ansible_kernel}}
deployment_packages:
  - python3-pip
sudo: sudo