- name: Update packages
  ansible.builtin.command: apt update -y
  become: yes

- name: Variables that are common across all OS types
  include_vars: "{{ lookup('first_found', dependencies) }}"
  vars:
    dependencies:
      files:
        - common.yml
      paths:
        - 'vars'

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', dependencies) }}"
  vars:
    dependencies:
      files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Install compile packages for bcc
  ansible.builtin.package:
    name: "{{ bcc_build_packages }}"
    state: present
  become: yes
  
- name: Install dependency packages for bcc tool tcpconnect
  ansible.builtin.package:
    name: "{{ tcpconnect_dependecies }}"
    state: present
  become: yes

- name: Set the PYTHONPATH environment variable to for automation scripts
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.profile
    regexp: '^export PYTHONPATH='
    line: export PYTHONPATH=$(dirname `find /usr/lib -name bcc`):$PYTHONPATH