---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # TODO: build prebuilt ansible images (use this one for now)
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible:latest}
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence: 
    - destroy
    - create
    - converge
    # - idempotence # TODO: enable idempotence
    - lint
    - verify